# Generated by Django 4.2.3 on 2023-08-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('checkin', models.CharField(max_length=200)),
                ('checkout', models.CharField(max_length=200)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
